# -*- coding: utf-8 -*-
"""STM's Copy of Data visualization Assignment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10wc6RHV0lcDEAvSUOfEdurLUySjgmbQ6

This assignment is on data visualization. Use the given dataset to answer the questions.
"""

import seaborn as sns

df = sns.load_dataset("titanic")
df.head()

"""1. Plot a graph of your choice to show the age distribution of the passengers on the Titanic. Which age demography was higher?
2. Display the gender of the passengers using an appropriate chart. Which gender demography was higher?
3. Show the classes available on the ship. Which class was most occupied?
4. Use a joint plot to explore the relationship between the age and fare.
"""

import pandas as pd
import matplotlib.pyplot as plt

"""# 1. Plot a graph of your choice to show the age distribution of the passengers on the Titanic. Which age demography was higher?"""

# Histogram graph to show the age distribution of the passengers on the Titanic

sns.histplot(data = df, x = "age", color = "#780de2")

plt.title("Histogram distribution of the age of 'Titanic passengers'")

"""*Which age demography was higher?*: The age group between 20-25

# 2. Display the gender of the passengers using an appropriate chart. Which gender demography was higher?
"""

# code to plot and customize a bar chart with the given variable

sns.set_theme(style = "darkgrid")
sns.countplot(x = "sex", data = df, palette = "Set2")

"""The male gender is obviously higher, with a count of above 550, compared to the female gender that is just a little above 300.

# Show the classes available on the ship. Which class was most occupied?
"""

#code to generate a frequency table showing the various ...
# categories in the "class" variable and the respective counts

freq_table = pd.crosstab(df["class"], columns = "count")

print(freq_table)

# code to plot and customize a corresponding pie chart
freq_table.plot.pie(subplots = True, autopct = '%.0f%%')
plt.legend().remove()

plt.show()

"""From the frequency table and the pie chart above, there are three classes on the ship - first, second, third - and the most occupied ship is the third, occupying more than half (55%) of the ship.

# Use a joint plot to explore the relationship between the age and fare.
"""

#Code to generate a jointplot of age and fare and customize it too
sns.set_theme(style="darkgrid")
sns.jointplot(data = df, x = "age", y = "fare", dropna = True,\
              kind = "reg", color = "#e9868b")

"""From the joint plot above, it is seen that the passengers' age is *slightly positively skewed* and their fares are *also positively skewed but more extreme than their ages*.


This means that most passengers are within the younger age frame (mostly between 20 and 40) and their fares are also mostly low (less than 300) except for the few with the "very high" fares (above 500).


When compared to each other, there is a *positive relationship* between them as evidenced by the direction of the correlation line in the scatterplot in the jointplot above.

However, this relationship can be considered as a *weak relationship* because of the distribution of the dots around the line. This is further supported by the correlation coefficient generated in the code line below.
"""

# code to calculate the Pearson's correlation coefficient between age and fare
# This quantifies the strength of the relationship between the two variables
# Expected range is -1 to +1; zero indicates no relationship
# + or - sign indicates the direction of the relationship
# the closer, the value is to zero, the weaker the relationship
# the farther away from zero and the closer to 1, the stronger the relationship

corr_coeff_age_and_fare = df["age"].corr(df["fare"])

round(corr_coeff_age_and_fare, 4)

"""The coefficient above shows only 0.0961 which is closer to zero than one, and can be interpreted as a 9.61% relationship between age and fare, which although it is positive, it is a very weak relationship, almost showing no relationship."""